apiVersion: v1
kind: ResourceQuota
metadata:
  name: intern-quota
  namespace: intern-test
spec:
  hard:
    pods: "3"
    requests.cpu: "1"
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 1Gi